version: '3.8'

services:
  postgresdb:
    container_name: postgresdb
    image: postgres
    environment:
      POSTGRES_USER: "rustdb"
      POSTGRES_PASSWORD: "rustdb"
      POSTGRES_DB: "rustcrud"
    volumes:
      - rust_api_data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    container_name: rust_backend
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://rustdb:rustdb@postgresdb:5432/rustcrud?sslmode=disable
    depends_on:
      - postgresdb
    networks:
      - app-network
  
volumes:
  rust_api_data: {}

networks:
  app-network:
    driver: bridge
