version: '3.8'

services:
  postgresdb:
    container_name: postgresdb
    image: postgres
    environment:
      POSTGRES_USER: "rustdb"
      POSTGRES_PASSWORD: "rustdb"
      POSTGRES_DB: "rustcrud"
    volumes:
        - rust_api_data:/var/lib/postgresql/data
  app:
    container_name: rust_backend
    build: 
      context: .
      network: host
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://rustdb:rustdb@localhost:5432/rustcrud?sslmode=disable
    depends_on:
      - postgresdb
  
volumes:
  rust_api_data: {}